// Public types. A provider consumes the provider-neutral **`@packkit/core`
// deployment contract**, never a language generator — support is `provider ×
// DeploymentContract`, not `provider × language`. A static site generated by
// create-packkit (JS), create-packkit-py, or create-packkit-go deploys the same
// way. A host passes plain objects; `type` stays a loose string so an unrecognized
// contract from a newer generator is reported unsupported, never a type error.

export interface StaticDeploymentContract {
	type: 'static';
	buildCommand: string;
	outputDirectory: string;
}

/** The language-neutral service/worker contract fields this provider reads. Ports
 *  and health paths come straight from `@packkit/core`'s contract — never inferred. */
export interface ServiceDeploymentContract {
	type: 'service';
	runtime: string;
	startCommand: string;
	defaultPort: number;
	portEnvironmentVariable: string;
	healthCheckPath: string;
	requiredEnvironmentVariables?: string[];
	optionalEnvironmentVariables?: string[];
}

export interface WorkerDeploymentContract {
	type: 'worker';
	runtime: string;
	startCommand: string;
	requiredEnvironmentVariables?: string[];
	optionalEnvironmentVariables?: string[];
}

/** Any `@packkit/core` deployment contract a host may hand us. Fields beyond `type`
 *  are optional so an unrecognized contract from a newer generator is reported
 *  unsupported, never a type error. */
export interface DeploymentContractLike {
	type: string;
	buildCommand?: string;
	outputDirectory?: string;
	runtime?: string;
	defaultPort?: number;
	portEnvironmentVariable?: string;
	healthCheckPath?: string;
	requiredEnvironmentVariables?: string[];
	optionalEnvironmentVariables?: string[];
	[key: string]: unknown;
}

/** The minimum a project object must carry for this provider to act on it. */
export interface ProjectLike {
	deploymentContract: DeploymentContractLike;
	[key: string]: unknown;
}

export interface UnsupportedReason {
	code: string;
	message: string;
}

export interface SupportResult {
	supported: boolean;
	reasons: UnsupportedReason[];
}

/** A GitHub repository, used to scope the OIDC trust policy (`repo:owner/name:…`)
 *  so only this repository's workflows can assume the deploy role. */
export interface RepositoryInput {
	owner: string;
	name: string;
	/** Branch that may run `apply` (plans run on any ref). Default `main`. */
	branch?: string;
}

export interface ResolvedRepository {
	owner: string;
	name: string;
	branch: string;
}

/** Options for shaping the emitted infrastructure. All have sane defaults except
 *  a `name` (the resource prefix) and the `repository` (needed to scope OIDC). */
export interface AwsPrepareOptions {
	/** Resource name prefix, e.g. `my-site`. Lowercased/hyphenated for AWS names. */
	name: string;
	/** AWS region. Default `us-east-1` (also required for CloudFront ACM certs). */
	region?: string;
	/** The GitHub repo whose Actions may assume the deploy role. If omitted, it is
	 *  emitted as a required Terraform variable the user fills in during bootstrap. */
	repository?: RepositoryInput;
}

export interface ResolvedAwsOptions {
	name: string;
	region: string;
	repository?: ResolvedRepository;
}

export interface PrepareResult {
	/** Relative path → file contents. The host writes these into the repo (ideally
	 *  via `@packkit/core/node`'s writer for path-safety). */
	files: Record<string, string>;
}

/** The deploy archetype the emitted infra implements — the AWS shape a contract
 *  maps to. `static` → CloudFront/S3, `service` → App Runner, `worker` → ECS Fargate. */
export type AwsArchetype = 'static-site' | 'service' | 'worker';

/** The provider-neutral fields read off a service contract, normalized. */
export interface ServiceView {
	port: number;
	portEnv: string;
	healthCheckPath: string;
	requiredEnv: string[];
	optionalEnv: string[];
	runtime: string;
}

/** The provider-neutral fields read off a worker contract, normalized. */
export interface WorkerView {
	requiredEnv: string[];
	optionalEnv: string[];
	runtime: string;
}

export interface AwsPlan {
	provider: 'aws';
	archetype: AwsArchetype;
	region: string;
	name: string;
	repository?: ResolvedRepository;
	/** The Terraform/pipeline files this plan would write. */
	files: Record<string, string>;
	/** A human-auditable description of what applying the emitted infra creates. */
	resources: string[];
}
